# Generated by Django 4.2 on 2023-04-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='end_date',
            new_name='deadline',
        ),
    ]
